export const LOGIN_FETCH_REQUEST = 'LOGIN_FETCH_REQUEST';
export const LOGIN_FETCH_SUCCESS = 'LOGIN_FETCH_SUCCESS';
export const LOGIN_FETCH_FAILURE = 'LOGIN_FETCH_FAILURE';

export const CONTACT_ADD = 'CONTACT_ADD';
export const CONTACT_REMOVE = 'CONTACT_REMOVE';